services:
  vector:
    image: altinity/clickhouse-server:25.8.9.20496.altinityantalya
    container_name: vector
    hostname: vector
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=eu-central-1
    depends_on:
      postgres-source:
        condition: service_healthy
      minio:
        condition: service_healthy
      ice-rest-catalog:
        condition: service_healthy
    volumes:
      - clickhouse-data/vector/clickhouse:/var/lib/clickhouse
      - clickhouse-logs/vector/log:/var/log/clickhouse-server
      - ./antalya/config.d/vector:/etc/clickhouse-server/config.d
      - ./antalya/users.d:/etc/clickhouse-server/users.d
    networks:
      - data-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keeper:
    image: altinity/clickhouse-keeper:25.8.9.20496.altinityantalya
    container_name: keeper
    hostname: keeper
    ports:
      - 9181:9181
    volumes:
      - clickhouse-data/keeper/keeper:/var/lib/keeper
      - clickhouse-logs/keeper/log:/var/log/clickhouse-keeper
      - ./antalya/config.d/keeper:/etc/clickhouse-keeper/keeper_config.d
    networks:
      - data-network

  swarm-1:
    image: altinity/clickhouse-server:25.8.9.20496.altinityantalya
    container_name: swarm-1
    hostname: swarm-1
    volumes:
      - clickhouse-data/swarm-1/clickhouse:/var/lib/clickhouse
      - clickhouse-logs/swarm-1/log:/var/log/clickhouse-server
      - ./antalya/config.d/swarm-1:/etc/clickhouse-server/config.d
      - ./antalya/users.d:/etc/clickhouse-server/users.d
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=eu-central-1
    networks:
      - data-network

  swarm-2:
    image: altinity/clickhouse-server:25.8.9.20496.altinityantalya
    container_name: swarm-2
    hostname: swarm-2
    volumes:
      - clickhouse-data/swarm-2/clickhouse:/var/lib/clickhouse
      - clickhouse-logs/swarm-2/log:/var/log/clickhouse-server
      - ./antalya/config.d/swarm-2:/etc/clickhouse-server/config.d
      - ./antalya/users.d:/etc/clickhouse-server/users.d
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=eu-central-1
    networks:
      - data-network

networks:
  data-network:
    external: true

volumes:
  clickhouse-data:
  clickhouse-logs: