services:
  ice-rest-catalog:
    image: altinity/ice-rest-catalog:${ICE_REST_CATALOG_TAG:-latest}
    container_name: ice-rest-catalog
    restart: unless-stopped
    ports:
      - 5000:5000
    configs:
      - source: ice-rest-catalog-yaml
        target: /etc/ice/ice-rest-catalog.yaml
    volumes:
      # for access to /var/lib/ice-rest-catalog/db.sqlite
      - ./data/ice-rest-catalog/var/lib/ice-rest-catalog:/var/lib/ice-rest-catalog
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - data-network
    healthcheck:
      disable: true

configs:
  ice-rest-catalog-yaml:
    content: |
      uri: jdbc:sqlite:file:/var/lib/ice-rest-catalog/db.sqlite?synchronous=OFF
      warehouse: s3://iceberg
      s3:
        endpoint: http://minio:9000
        pathStyleAccess: true
        accessKeyID: admin
        secretAccessKey: password
        region: eu-central-1
      bearerTokens:
        - value: foo
      anonymousAccess:
         enabled: true

networks:
  data-network:
    external: true