services:
  ice-rest-catalog:
    image: altinity/ice-rest-catalog:0.16.0
    restart: unless-stopped
    ports:
      - 5000:5000 # iceberg/http
    configs:
      - source: ice-rest-catalog-yaml
        target: /etc/ice/ice-rest-catalog.yaml
    volumes:
      # for access to /var/lib/ice-rest-catalog/db.sqlite
      - ./data/ice-rest-catalog/var/lib/ice-rest-catalog:/var/lib/ice-rest-catalog
    depends_on:
      - minio

configs:
  ice-rest-catalog-yaml:
    content: |
      uri: jdbc:sqlite:file:/var/lib/ice-rest-catalog/db.sqlite?journal_mode=WAL&synchronous=OFF&journal_size_limit=500
      warehouse: s3://iceberg
      s3:
        endpoint: http://minio:9000
        pathStyleAccess: true
        accessKeyID: admin
        secretAccessKey: password
        region: eu-central-1
      bearerTokens:
        - value: foo